# Generated by Django 5.0.3 on 2025-07-31 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('email_id', models.EmailField(max_length=254)),
                ('linkedIn', models.URLField()),
                ('gitHub', models.URLField()),
                ('experience', models.CharField(max_length=300)),
                ('about_me', models.CharField(blank=True, max_length=300, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('current_city', models.CharField(max_length=30)),
                ('current_state', models.CharField(max_length=30)),
                ('current_country', models.CharField(max_length=40)),
                ('permanent_city', models.CharField(blank=True, max_length=30, null=True)),
                ('permanent_state', models.CharField(blank=True, max_length=30, null=True)),
                ('permanent_country', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=30)),
                ('reward', models.CharField(max_length=20)),
                ('MyProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraactivity', to='api.myprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30)),
                ('project_discription', models.CharField(max_length=500)),
                ('project_start_at', models.DateField(blank=True, null=True)),
                ('project_end_at', models.DateTimeField(blank=True, null=True)),
                ('project_status', models.CharField(choices=[('finished', 'Finished'), ('on_going', 'On Going')], max_length=10)),
                ('project_link', models.URLField(blank=True, null=True)),
                ('MyProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='api.myprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deg_name', models.CharField(max_length=30)),
                ('college', models.CharField(max_length=60)),
                ('passing_year', models.CharField(max_length=10)),
                ('percent', models.PositiveIntegerField()),
                ('MyProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification', to='api.myprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('MyProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='api.myprofile')),
            ],
        ),
    ]
