services:
  - type: web
    name: ashraf
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backendfolio.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
